// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// c_plane_dist
NumericMatrix c_plane_dist(NumericVector x, NumericVector y, IntegerVector from, IntegerVector to);
RcppExport SEXP _sphere_c_plane_dist(SEXP xSEXP, SEXP ySEXP, SEXP fromSEXP, SEXP toSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type from(fromSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type to(toSEXP);
    rcpp_result_gen = Rcpp::wrap(c_plane_dist(x, y, from, to));
    return rcpp_result_gen;
END_RCPP
}
// c_sphere_dist
NumericMatrix c_sphere_dist(NumericVector lat, NumericVector lon, IntegerVector from, IntegerVector to);
RcppExport SEXP _sphere_c_sphere_dist(SEXP latSEXP, SEXP lonSEXP, SEXP fromSEXP, SEXP toSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type lat(latSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lon(lonSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type from(fromSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type to(toSEXP);
    rcpp_result_gen = Rcpp::wrap(c_sphere_dist(lat, lon, from, to));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sphere_c_plane_dist", (DL_FUNC) &_sphere_c_plane_dist, 4},
    {"_sphere_c_sphere_dist", (DL_FUNC) &_sphere_c_sphere_dist, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_sphere(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
