# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_plane_dist <- function(x, y, from, to) {
    .Call('_sphere_c_plane_dist', PACKAGE = 'sphere', x, y, from, to)
}

c_sphere_dist <- function(lat, lon, from, to) {
    .Call('_sphere_c_sphere_dist', PACKAGE = 'sphere', lat, lon, from, to)
}

